name: corextra
description: Handy Dart extensions and utility functions for easier coding.
version: 1.0.0
homepage: https://github.com/ashiq-dev-codes/corextra.git
repository: https://github.com/ashiq-dev-codes/corextra.git

environment:
  sdk: ^3.8.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
